name: puredartlua
description: Lua 5.5 interpreter and autodoc tool written in pure Dart.
version: 1.0.0
repository: https://github.com/TheMaverickProgrammer/DartLua

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0
  colorize: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
